GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Sarunphat saggy",
    "email": "saggy@gmail.com",
    "gender": "Male"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Morn Nakek",
    "email": "kek@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:5000/users/2